#!/bin/bash
# loaded by dependency order

# outputs

msg_warn() {
  echo -e "\e[33mwarning:\e[0m $*"
}
msg_info() {
  echo -e "\e[36minfo:\e[0m $*"
}
msg_ok() {
  echo -e "\e[32mfinished\e[0m"
}
exitWithError() {
  echo -e "\e[91m\e[1merror:\e[0m $*" >>/dev/stderr
  exit 1
}

##########################

checkParamsExact() {
  if [ $1 -ne $2 ]; then
    exitWithError "$2 params required, $1 provided"
  fi
}

isArch() {
  if [ ! -f "/etc/arch-release" ]; then
    exitWithError "not arch linux"
  fi
}

emptyAndDeleteFolder() {
  if [ -d "$1" ]; then
    find $1 -empty -delete
  fi
}
