#!/bin/bash

#
# Packages
#
# sudo pacman --sync --clean --noconfirm
pikaur -Scc --noconfirm
sudo pacman -Sc --noconfirm
sudo pacman -Scc --noconfirm
# sudo pacman --database --check --quiet
pikaur -Dk

#
# Flatpak
#
if [ -x "$(command -v flatpak)" ]
  then
    flatpak uninstall --delete-data
    flatpak --unused uninstall --delete-data
fi

#
# Journal
#
sudo journalctl -q --vacuum-time=1h > /dev/null

#
# Bash history
#
history -c

#
# Files
#
# Delete empty files and folders:
find $HOME/.cache $HOME/.local -empty -delete
# fix mozilla
# find $HOME/.cache $HOME/.local $HOME/.mozilla -empty -delete

# Delete empty folders only:
find $HOME/.config -type d -empty -delete

rm -f $HOME/.bash_history 
rm -f $HOME/.bash_logout # Commants to run on BASH logout
rm -f $HOME/.cache/pikaur/*
rm -f $HOME/.config/vlc/vlc-qt-interface.conf # vlc recent videos
rm -f $HOME/.dmrc # Legacy GNOME2 default user session
rm -f $HOME/.esd_auth # Pulseaudio cookie
rm -f $HOME/.fontconfig # has CACHEDIR.TAG in it 
rm -f $HOME/.lesshst # .less-history-file
rm -f $HOME/.mysql_history
rm -f $HOME/.netrc # for heroku
rm -f $HOME/.node_repl_history
rm -f $HOME/.python-history
rm -f $HOME/.Rhistory # R Lang's/CLI's history
rm -f $HOME/.vuerc
rm -f $HOME/.xsession-errors*
rm -f $HOME/.yarnrc

rm -fr $HOME/.cache/thumbnails
rm -fr $HOME/.config/chromium/Default/Service\ Worker/*
rm -fr $HOME/.docker # auth setings
rm -fr $HOME/.java # java settings
rm -fr $HOME/.local/share/pikaur/aur_repos
rm -fr $HOME/.putty
rm -fr $HOME/.screenlayout # prob for arandr/xrandr
rm -fr $HOME/.subversion
rm -fr $HOME/.thumbnails
rm -fr $HOME/.uml

# Hotfix for vlc subtitles
mkdir -p $HOME/.cache/vlc


#
# Tmp
#

# a better way to do this?
# rm -fr $HOME/.config/chromium/Profile\ 1/Service\ Worker/*
# rm -fr $HOME/.config/chromium/Profile\ 2/Service\ Worker/*
# rm -fr $HOME/.config/chromium/Profile\ 3/Service\ Worker/*
# rm -fr $HOME/.config/chromium/Profile\ 6/Service\ Worker/*
# rm -fr $HOME/.config/chromium/Profile\ 7/Service\ Worker/*
# rm -fr $HOME/.config/chromium/Profile\ 9/Service\ Worker/*
# rm -fr $HOME/.config/chromium/Profile\ 10/Service\ Worker/*

# if [ $# -ne 0 ] # If has any parameter
#   then
#     rm -fr $HOME/.cache
#     rm -fr $HOME/.npm
#     rm -fr $HOME/.node-gyp

#     # Requires restart
#     rm -f $HOME/.ICEauthority # X11 Auth Client2Client
#     rm -f $HOME/.Xauthority # X11 Auth Client2Server
# fi

