#!/bin/bash

set -e
util-bash-checkparamcount $# 0

util-log "debug" "cece" "Init"

#
# Packages
#
util-log "debug" "cece" "Running: pikaur -Scc --noconfirm"
pikaur -Scc --noconfirm > /dev/null

util-log "debug" "cece" "Running: sudo pacman -Sc --noconfirm"
sudo pacman -Sc --noconfirm > /dev/null

util-log "debug" "cece" "Running: sudo pacman -Scc --noconfirm"
sudo pacman -Scc --noconfirm > /dev/null

util-log "debug" "cece" "Running: pikaur -Dk"
pikaur -Dk > /dev/null

#
# Flatpak
#
util-log "debug" "cece" "Checking for flatpak"
if [ -x "$(command -v flatpak)" ]
  then
    util-log "debug" "cece" "Running: flatpak uninstall --delete-data"
    flatpak uninstall --delete-data

    util-log "debug" "cece" "Running: flatpak --unused uninstall --delete-data"
    flatpak --unused uninstall --delete-data
fi

#
# Journal
#
util-log "debug" "cece" "Running: sudo journalctl -q --vacuum-time=1h"
sudo journalctl -q --vacuum-time=1h > /dev/null

#
# Bash history
#
util-log "debug" "cece" "Running: history -c"
history -c > /dev/null

#
# Files
#
# Delete empty files and folders:
FILES_TO_DELETE=(
  # Bash
  ".bash_history"
  ".bash_logout" # Commants to run on BASH logout
  # Chromium
  ".config/chromium/Default/Service\ Worker/*"
  # Docker
  ".docker" # auth setings
  # Fontconfig
  ".fontconfig" # has CACHEDIR.TAG in it 
  # GNOME
  ".dmrc" # Legacy GNOME2 default user session
  # Heroku
  ".netrc" # for heroku
  # Java
  ".java" # java settings
  # Less
  ".lesshst" # .less-history-file
  # MySQL
  ".mysql_history"
  # Node.js
  ".node_repl_history"
  # Pikaur
  ".cache/pikaur/*"
  ".local/share/pikaur/aur_repos"
  # PostgreSQL
  ".psql_history"
  # Python
  ".python-history"
  # Pulseaudio
  ".esd_auth" # Pulseaudio cookie
  # Putty
  ".putty"
  # P
  ".Rhistory" # R Lang's/CLI's history
  # Tumblr
  ".cache/thumbnails"
  ".thumbnails"
  # Subversion
  ".subversion"
  # Xorg
  ".local/share/xorg/Xorg.0.log*"
  ".screenlayout" # prob for arandr/xrandr
  ".xsession-errors*"
  # VLC
  ".config/vlc/vlc-qt-interface.conf" # vlc recent videos
  # Vue.js
  ".vuerc"
  # Yarn
  ".yarnrc"
  # VSCODE Web Template Studio Extension
  ".local/share/WebTS\Logs/*.log" #ms webts web template studio"
  # Other
  ".uml"
)
util-log "debug" "cece" "Removing files & folders"
for i in "${FILES_TO_DELETE[@]}"; do
  rm -rf "$HOME/$i"
done

#
# Empty folders
#
util-log "debug" "cece" "Emptying folders"
FILES_TO_CLEAN=(
  "$HOME/.cache"
  "$HOME/.local"
  "$HOME/.config"
)
util-folder-empty FILES_TO_CLEAN > /dev/null

#
# VLC
#
util-log "debug" "cece" "Removing ~/.cache/vlc"
mkdir -p $HOME/.cache/vlc > /dev/null # for subtitles

#
# Chrome
#
# $HOME/.config/chromium/Profile\ */Service\ Worker/*

#
# Delete carefully
#
# .cache
# .ICEauthority # X11 Auth Client2Client - Requires restart
# .node-gyp
# .npm
# .Xauthority # X11 Auth Client2Server - Requires restart

util-log "debug" "cece" "Done."
