#!/bin/bash

util-log "debug" "recipe" "Started"

# params
set -e
util-bash-checkparamcount $# 2
MODE=$1
APPNAME=$2

util-log "debug" "recipe" "MODE=$MODE APPNAME=$APPNAME"

RECIPEFILE=""
HASRECIPE=false

checkRecipe() {
  util-log "debug" "recipe.check" "Determining recipe file for '$APPNAME'"

  local APPFILE="$kb/os/scripts/recipes/$1.sh"

  util-log "debug" "recipe.check" "Trying to load '$APPFILE'"

  if [ -f "$APPFILE" ]; then
    util-log "info" "recipe.check" "Recipe file exists"
    HASRECIPE=true
  else
    util-log "warn" "recipe.check" "Recipe file does not exist"
  fi
}

checkRecipe $APPNAME

params=(
  "aa"
  "bb"
)
echo "p=$params"

# if [ $MODE =]

# if [ $MODE == "install" ]; then
#   util-log "debug" "recipe.install" "Init"

#   if [ $HASRECIPE = true ]; then
#     util-log "debug" "recipe.install" "Has recipe file. Calling 'util-pacman-install'"
#     util-recipe-install $RECIPEFILE
#   else
#     util-log "warn" "recipe.install" "No recipe file. Calling 'pikaur -S --needed'"
#     pikaur -S --needed $APPNAME
#   fi
# fi

# if [ $MODE == "install" ]; then
#   util-log "debug" "recipe.install" "Init"

#   if [ $HASRECIPE = true ]; then
#     util-log "debug" "recipe.install" "Has recipe file. Calling 'util-pacman-install'"
#     util-recipe-install $RECIPEFILE
#   else
#     util-log "warn" "recipe.install" "No recipe file. Calling 'pacman -Rscnu'"
#     pikaur -Rscnu $APPNAME
#   fi
# fi
