#!/bin/bash

util-log "debug" "recipe" "Started"

# params
set -e
util-bash-checkparamcount $# 2
MODE=$1
APPNAME=$2

util-log "debug" "recipe" "MODE='$MODE' APPNAME='$APPNAME'"

RECIPEFILE=""


HASRECIPE=false

checkRecipe() {
  RECIPEFILE="$kb/os/scripts/recipes/$1.sh"

  util-log "debug" "recipe.checkRecipe" "Trying to load '$RECIPEFILE'"

  if [ -f "$RECIPEFILE" ]; then
    HASRECIPE=true
    util-log "info" "recipe.checkRecipe" "Recipe file exists"
  else
    util-log "info" "recipe.checkRecipe" "Recipe file does not exist"
  fi
}

checkRecipe $APPNAME

if [ $MODE == "uninstall" ]; then
  if [ $HASRECIPE = true ]; then
    util-log "info" "recipe" "Has recipe file. Calling 'util-recipe-uninstall $RECIPEFILE'"

    if util-recipe-uninstall $RECIPEFILE ; then
      util-log "info" "recipe" "recipe removal success"
    else
      util-log "error" "recipe" "recipe removal failed"
    fi
  else
    util-log "info" "recipe" "No recipe file. Calling 'pikaur -Rscnu $APPNAME'"

    if pikaur -Rscnu $APPNAME ; then
      util-log "info" "recipe" "pikaur removal success"
    else
      util-log "error" "recipe" "pikaur removal failed"
    fi
  fi
fi

# if [ $MODE == "install" ]; then
#   util-log "debug" "recipe.install" "Init"

#   if [ $HASRECIPE = true ]; then
#     util-log "debug" "recipe.install" "Has recipe file. Calling 'util-pacman-install'"
#     util-recipe-install $RECIPEFILE
#   else
#     util-log "warn" "recipe.install" "No recipe file. Calling 'pacman -Rscnu'"
#     pikaur -Rscnu $APPNAME
#   fi
# fi

util-log "debug" "recipe" "Done"
