#!/bin/bash
. "$kb/os/bashset/init.sh"

checkParamsExact $# 1

# main

# delete package
Cmd="pikaur -Rscnu --color auto $1"
$Cmd
CmdStatus=$?

if [ $CmdStatus -eq 0 ]; then
# clear cache
  CLEARCACHE="$(dirname "$(readlink -f "$0")")/cece"
  msg_info "clearing cache by running $CLEARCACHE"
  . "$CLEARCACHE" &> /dev/null
  msg_info "cleared cache"
else
  msg_warn "pikaur command not successful, will not run clearcache"
fi

# clean
CLEANFILE="$(dirname $(dirname "$(readlink -f "$0")"))/uninstallers/$1.sh"
msg_info "Checking if clean file exists: $CLEANFILE"

if test -f "$CLEANFILE"; then
  msg_info "found uninstall cleaner file: $CLEANFILE"
  . "$CLEANFILE"
  msg_info "cleaned"
else
  msg_warn "no clean file found: $CLEANFILE"
fi

msg_ok "Finished"