#!/bin/bash
source _fn

checkParamsExact $# 1

# main

# delete package
Cmd="pikaur -Rscnu --color auto $1"
$Cmd
CmdStatus=$?

if [ $CmdStatus -ne 0 ]; then
  exit
fi

# clean
CLEANFILE="$(dirname "$(readlink -f "$0")")/../uninstallers/$1.sh"

if test -f "$CLEANFILE"; then
  msg_info "found uninstall cleaner file: $CLEANFILE"
  . "$CLEANFILE"
  msg_info "cleaned"
else
  msg_warn "no clean file found: $CLEANFILE"
fi

# clear cache
CLEARCACHE="$(dirname "$(readlink -f "$0")")/clearcache"
msg_info "clearing cache by running $CLEARCACHE"
. "$CLEARCACHE" &> /dev/null
msg_info "cleared cache"

# end
msg_ok
