#!/bin/bash
set -e


util-log "debug" "util-folder-empty" "Init $1"
util-bash-checkparamcount $# 1
util-log "debug" "util-folder-empty" "Emptying $1"

# if given folder exists

if [ -d "$1" ]; then

  # remove empty files and folders (includes given folder)
  find $1 -empty -delete
fi
