#!/bin/bash
set -e
. "$kb/os/util/colors"



util-bash-checkparamcount $# 1
GROUPNAME=$1


util-log "debug" "group-delete" "Checking if group '$GROUPNAME' exists... " true
if [ ! $(getent group $GROUPNAME) ]; then
  PrintColor "info" "No"
  exit
else
  PrintColor "info" "Yes"
fi


util-log "debug" "group-delete" "Deleting group '$GROUPNAME'... " true
if sudo groupdel $GROUPNAME > /dev/null; then
  PrintColor "info" "Done"
else
  PrintColor "error" "FAILED"
fi


util-log "debug" "group-delete" "Done"
