#!/bin/bash

set -e
# util-bash-checkparamcount $# 3

. "$kb/os/util/colors"

LEVEL=$1
SRC=$2
MSG=$3

declare -A logColors=(
  ["info"]=$C_256_Info
  ["debug"]=$C_256_Debug
  ["warn"]=$C_256_Yellow
  ["error"]=$C_Red
)

COLOR="${logColors[$LEVEL]}"
DATESTR="$(date '+%T.%3N')"

if [ $LEVEL == "error" ]; then
  >&2 echo -e "$DATESTR $SRC: ${COLOR}${MSG}${F_Reset}"
else
  echo -e "$DATESTR $SRC: ${COLOR}${MSG}${F_Reset}"
fi
