. "$kb/os/bashset/var-colors.sh"

. "$kb/os/bashset/fn-file.sh"
. "$kb/os/bashset/fn-group.sh"
. "$kb/os/bashset/fn-import.sh"
. "$kb/os/bashset/fn-msg.sh"
. "$kb/os/bashset/fn-other.sh"
. "$kb/os/bashset/fn-params.sh"
. "$kb/os/bashset/fn-pkg.sh"
. "$kb/os/bashset/fn-systemctl.sh"
